version: '3.8'

services:
  web:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true