version: "3.8"

services:
  web:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: npm start
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
